#!/bin/bash

bundle exec vagrant destroy -f

ln -nfs bootstrap.sh vagrant.sh
bundle exec vagrant up

ln -nfs guest_additions.sh vagrant.sh
sleep 5
bundle exec vagrant reload

ln -nfs guest_additions.sh microwave.sh
