#!/bin/bash

export EC2_HOME="$AWSME_CLI/ec2"
export AWS_CLOUDFORMATION_HOME="$AWSME_CLI/cfn"
export AWS_AUTO_SCALING_HOME="$AWSME_CLI/as"
export AWS_IAM_HOME="$AWSME_CLI/iam"
export AWS_ELB_HOME="$AWSME_CLI/elb"
export AWS_ELASTICACHE_HOME="$AWSME_CLI/elasticache"
export AWS_CLOUDWATCH_HOME="$AWSME_CLI/mon"
export CS_HOME="$AWSME_CLI/cs"
export AWS_RDS_HOME="$AWSME_CLI/rds"

: ${AWS_DEFAULT_REGION:=us-west-1}
export AWS_DEFAULT_REGION
export EC2_URL="ec2.${AWS_DEFAULT_REGION}.amazonaws.com"

: ${JAVA_HOME:="$(/usr/libexec/java_home 2>&-)"}
export JAVA_HOME

if [[ -z "$JAVA_HOME" ]]; then
  JAVA_HOME="$(dirname $(dirname $(readlink -f /usr/bin/java)))"
fi

if [[ -z "$JAVA_HOME" ]]; then
  logger_fatal "specify java install in environment variable JAVA_HOME"
  exit 1
fi

AWS_CREDENTIAL_FILE="$AWSME/config/aws.txt"
export AWS_CREDENTIAL_FILE

if [[ -z "$AWS_CREDENTIAL_FILE" ]]; then
  logger_fatal "specify your aws keys in config/aws.txt"
  exit 1
fi

AWS_SECRET_KEY="$(ryaml $AWSME/config/aws.yml aws_secret_access_key)"
if [[ -z "$AWS_SECRET_KEY" ]]; then
  AWS_SECRET_KEY="$(ryaml $AWSME/config/aws.yml AWS_SECRET_KEY)"
fi
export AWS_SECRET_KEY

if [[ -z "$AWS_SECRET_KEY" ]]; then
  logger_fatal "specify your aws secret key in environment variable AWS_ACCESS_KEY or in config/aws.yml"
  exit 1
fi

AWS_ACCESS_KEY="$(ryaml $AWSME/config/aws.yml aws_access_key_id)"
if [[ -z "$AWS_ACCESS_KEY" ]]; then
  AWS_ACCESS_KEY="$(ryaml $AWSME/config/aws.yml AWS_ACCESS_KEY)"
fi
export AWS_ACCESS_KEY

if [[ -z "$AWS_ACCESS_KEY" ]]; then
  logger_fatal "specify your aws access key in environment variable AWS_ACCESS_KEY or in config/aws.yml"
  exit 1
fi

awshome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
PATH="$EC2_HOME/bin:$AWS_CLOUDFORMATION_HOME/bin:$AWS_AUTO_SCALING_HOME/bin:$AWS_ELB_HOME/bin:$AWS_IAM_HOME/bin:$AWS_ELASTICACHE_HOME/bin:$AWS_CLOUDWATCH_HOME/bin:$CS_HOME/bin:$AWS_RDS_HOME/bin:$PATH:$awshome/bin"
