#!/bin/bash

if [[ "$#" > 0 ]]; then
  AWSME="$1"; shift
else
  : ${AWSME:="$(cd -P -- "$(dirname -- "${BASH_SOURCE}")/.." && pwd -P)"}
fi

export AWSME

PATH="$PATH:${AWSME}/libexec"

export EC2_HOME="$AWSME/vendor/projects/ec2"
export AWS_CLOUDFORMATION_HOME="$AWSME/vendor/projects/cfn"
export AWS_AUTO_SCALING_HOME="$AWSME/vendor/projects/as"
export AWS_IAM_HOME="$AWSME/vendor/projects/iam"
export AWS_ELB_HOME="$AWSME/vendor/projects/elb"
export AWS_ELASTICACHE_HOME="$AWSME/vendor/projects/elasticache"
export AWS_CLOUDWATCH_HOME="$AWSME/vendor/projects/mon"

: ${JAVA_HOME:="$(/usr/libexec/java_home 2>&-)"}
export JAVA_HOME

if [[ -z "$JAVA_HOME" ]]; then
  JAVA_HOME="$(dirname $(dirname $(readlink -f /usr/bin/java)))"
fi

if [[ -z "$JAVA_HOME" ]]; then
  logger_fatal "specify java install in environment variable JAVA_HOME"
  exit 1
fi

AWS_CREDENTIAL_FILE="$AWSME/config/aws.txt"
export AWS_CREDENTIAL_FILE

if [[ -z "$AWS_CREDENTIAL_FILE" ]]; then
  logger_fatal "specify your aws keys in config/aws.txt"
  exit 1
fi

AWS_SECRET_KEY="$(ryaml $AWSME/config/aws.yml AWS_SECRET_KEY)"
export AWS_SECRET_KEY

if [[ -z "$AWS_SECRET_KEY" ]]; then
  logger_fatal "specify your aws secret key in environment variable AWS_ACCESS_KEY or in config/aws.yml"
  exit 1
fi

AWS_ACCESS_KEY="$(ryaml $AWSME/config/aws.yml AWS_ACCESS_KEY)"
export AWS_ACCESS_KEY

if [[ -z "$AWS_ACCESS_KEY" ]]; then
  logger_fatal "specify your aws access key in environment variable AWS_ACCESS_KEY or in config/aws.yml"
  exit 1
fi

EC2_PRIVATE_KEY="$AWSME/config/private-key.pem"
export EC2_PRIVATE_KEY

if [[ -z "EC2_PRIVATE_KEY" ]]; then
  logger_fatal "specify your ec2 private certificate in environment variable EC2_PRIVATE_KEY or put in config/private-key.pem"
  exit 1
fi

EC2_CERT="$AWSME/config/certificate.pem"
export EC2_CERT

if [[ -z "EC2_CERT" ]]; then
  logger_fatal "specify your ec2 public certificate in environment variable EC2_CERT or put in config/certificate.pem"
  exit 1
fi

PATH="$EC2_HOME/bin:$AWS_CLOUDFORMATION_HOME/bin:$AWS_AUTO_SCALING_HOME/bin:$AWS_ELB_HOME/bin:$AWS_IAM_HOME/bin:$AWS_ELASTICACHE_HOME/bin:$AWS_CLOUDWATCH_HOME/bin:$PATH"
