#!/bin/bash

# parse the command-line
DEFINE_string "boxname" "" "Vagrant box name"
DEFINE_string "bootstrap" "$shome/bootstrap/ubuntu.sh" "Initial bootstrap script"
DEFINE_string 'release' 'precise' 'Ubuntu release'
DEFINE_boolean 'demo' "$FLAGS_FALSE" "Launch a demo instance and ssh in"
DEFINE_string 'sshopts' "" "ssh options during a demo"
DEFINE_string "output" "" "Where to bundle the vagrant box"

function until_port_open {
  local address="$1"; shift
  local port="$1"; shift

  logger_info "until $address:$port"

  while true; do
    if nc -z "$address" "$port"; then
      echo
      break
    fi
    echo -n "."
    sleep 5
  done
}

function build_vagrant {
  local release_dir="$shome/vagrant-$(build_type)-$(date +%Y%m%d-%H%M-$$)"

  mkdir -p $release_dir

  local nm_keypair="$(build_keypair)"
  
  bootstrap_ubuntu "$nm_keypair"
  early_termination
  local id_image="$(bundle_vagrant)"

  if [[ "$FLAGS_demo" = "$FLAGS_TRUE" ]]; then
    demo_vagrant "$nm_keypair" "$id_image" "$@"
  fi

  delete_keypair "$nm_keypair"
  rm -rf "$release_dir"
}
