#!/bin/bash

# parse the command-line
DEFINE_string 'region' 'us-east-1' 'AWS region' 'R'
DEFINE_string 'disk' 'ebs' 'AWS disk type' 'B'
DEFINE_string 'arch' 'amd64' 'AWS arch' 'a'
DEFINE_string 'instype' 'm1.large' "AWS instance type" "T"
DEFINE_string 'release' 'precise' 'Ubuntu release' 'U'
DEFINE_string 'sshauth' "$HOME/.ssh/authorized_keys" 'Authorized ssh keys' 's'

function until_port_open {
  local address="$1"; shift
  local port="$1"; shift

  logger_info "until $address:$port"

  while true; do
    if nc -z "$address" "$port"; then
      echo
      break
    fi
    echo -n "."
    sleep 5
  done
}

function build_vagrant {
  local release_dir="$shome/vagrant-$(build_type)-$(date +%Y%m%d-%H%M-$$)"

  mkdir -p $release_dir

  local nm_keypair="$(build_keypair)"
  
  import_ubuntu
  bootstrap_ubuntu "$nm_keypair"
  early_termination
  local id_image="$(bundle_vagrant)"
  demo_vagrant "$nm_keypair" "$id_image" "$@"

  delete_keypair "$nm_keypair"
}
