#!/bin/bash

function demo_in_vagrant {
  local pth_custom="$1"; shift

  local tmp_ssh_config="$(mktemp -t XXXXXXXXX)"
  (cd $release_dir && bundle exec vagrant ssh-config > "$tmp_ssh_config")
  $pth_custom "$tmp_ssh_config" "$@"
  rm -f "$tmp_ssh_config"
}

function build_vagrant {
  local release_dir="$shome/vagrant-$(build_type)-$(date +%Y%m%d-%H%M-$$)"

  mkdir -p $release_dir

  local nm_keypair="$(build_keypair)"
  
  import_ubuntu
  local id_image="$(clean_id_image)"
  demo_vagrant "$nm_keypair" "$id_image" "$@"
}
