#!/bin/bash

#/ NAME
#/     build vagrant -- builds a vagrant box
#/
#/ SYNOPSIS
#/   bin/build vagrant
#/
#/ EXAMPLES
#/     $ bin/build vagrant

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require awsme
require build

# entry point
function main {
  cd $shome
  time build_vagrant
}

function conf_virtualbox {
  local nm_box="$1"; shift
  local pth_script="$1"; shift
  $shome/bin/cook -j <(echo '{"run_list": ["vagrant::virtualbox"], "vagrant": { "box": "'"$nm_box"'", "provision": { "shell": { "path": "'"$pth_script"'" }} }}')
}

function build_vagrant {
  local id_instance

  # import ubuntu box and destroy lingering vagrant
  bundle exec vagrant box add precise-server-cloudimg-amd64 $shome/boxes/precise-server-cloudimg-amd64-vagrant-disk1.box || true
  conf_virtualbox "precise-server-cloudimg-amd64"
  bundle exec vagrant destroy -f

  # bootstrap until powered off
  conf_virtualbox "precise-server-cloudimg-amd64" "$shome/bootstrap/ubuntu.sh"
  bundle exec vagrant up
  id_instance="$(cat $shome/.vagrant/machines/default/virtualbox/id)"
  until_vbox "poweroff"

  # virtualbox guest additions with updated kernel
  conf_virtualbox "precise-server-cloudimg-amd64" "$shome/bootstrap/virtualbox.sh"
  bundle exec vagrant up
  id_instance="$(cat $shome/.vagrant/machines/default/virtualbox/id)"
  until_vbox "running"

  # cleanup and power off
  conf_virtualbox "precise-server-cloudimg-amd64" "$shome/bootstrap/finished.sh"
  bundle exec vagrant provision
  until_vbox "poweroff"

  # bundling
  bundle exec vagrant package --output $shome/boxes/awsme.box.tmp
  mv -f $shome/boxes/awsme.box.tmp $shome/boxes/awsme.box
  bundle exec vagrant box remove awsme virtualbox || true
  bundle exec vagrant box add awsme $shome/boxes/awsme.box
  bundle exec vagrant destroy -f

  # boot up new box
  conf_virtualbox "awsme" "$shome/bootstrap/noop.sh"
  bundle exec vagrant up
  id_instance="$(cat $shome/.vagrant/machines/default/virtualbox/id)"
  until_vbox "running"
  time until_port_open localhost "$(forwarded_ssh_port)"
  bundle exec vagrant ssh
}

require sub "$BASH_SOURCE" "$@"
