#!/bin/bash

#/ NAME
#/     build vagrant -- builds a vagrant box
#/
#/ SYNOPSIS
#/   bin/build vagrant
#/
#/ EXAMPLES
#/     $ bin/build vagrant

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require awsme
require build

# entry point
function main {
  local opt_ssh=

  if [[ "$FLAGS_sshagent" = "$FLAGS_TRUE" ]]; then
    opt_ssh="$opt_ssh -A"
  fi

  time build_vagrant
}

function forwarded_ssh_port {
  VBoxManage showvminfo "$id_instance" --machinereadable | awk '$1 ~ /^Forwarding\(.*?,22"/ { split($1,a,","); print a[4] }'
}

function build_vagrant {
  cd $shome

  local id_instance

  bundle exec vagrant box add precise-server-cloudimg-amd64 boxes/precise-server-cloudimg-amd64-vagrant-disk1.box || true
  bundle exec microwave -j <(echo '{"run_list": ["vagrant"], "vagrant": { "box": "precise-server-cloudimg-amd64" }}')
  bundle exec vagrant destroy -f

  # bootstrap
  bundle exec microwave -j <(echo '{"run_list": ["vagrant"], "vagrant": { "box": "precise-server-cloudimg-amd64", "provision": { "shell": { "path": "bootstrap/bootstrap.sh" }}}}')
  bundle exec vagrant up
  id_instance="$(bundle exec ruby -e 'require "json"; puts JSON.load(File.read(".vagrant"))["active"]["default"]')"
  until_vbox "poweroff"

  # guest additions
  bundle exec microwave -j <(echo '{"run_list": ["vagrant"], "vagrant": { "box": "precise-server-cloudimg-amd64", "provision": { "shell": { "path": "bootstrap/guest_additions.sh" }}}}')
  bundle exec vagrant up

  # bundling
  bundle exec microwave -j <(echo '{"run_list": ["vagrant"], "vagrant": { "box": "precise-server-cloudimg-amd64", "provision": { "shell": { "path": "bootstrap/finished.sh" }}}}')
  bundle exec vagrant provision
  bundle exec vagrant package
  mv package.box boxes/awsme.box
  bundle exec vagrant box remove awsme || true
  bundle exec vagrant box add awsme boxes/awsme.box
  bundle exec vagrant destroy -f

  # boot up new box
  bundle exec microwave -j <(echo '{"run_list": ["vagrant"], "vagrant": { "box": "awsme" }}')
  bundle exec vagrant up
  id_instance="$(bundle exec ruby -e 'require "json"; puts JSON.load(File.read(".vagrant"))["active"]["default"]')"
  until_vbox "running"
  time until_port_open localhost "$(forwarded_ssh_port)"
  bundle exec vagrant ssh
}

require sub "$BASH_SOURCE" "$@"
