#!/bin/bash

#/ NAME
#/     build vagrant -- builds a vagrant box
#/
#/ SYNOPSIS
#/   bin/build vagrant
#/
#/ EXAMPLES
#/     $ bin/build vagrant

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require awsme
require build

# entry point
function main {
  cd $shome
  time build_vagrant
}

function build_vagrant {
  local id_instance

  bundle exec vagrant box add precise-server-cloudimg-amd64 boxes/precise-server-cloudimg-amd64-vagrant-disk1.box || true
  bin/cook -j <(echo '{"run_list": ["vagrant"], "vagrant": { "box": "precise-server-cloudimg-amd64" }}')
  bundle exec vagrant destroy -f

  # bootstrap
  bin/cook -j <(echo '{"run_list": ["vagrant"], "vagrant": { "box": "precise-server-cloudimg-amd64", "provision": { "shell": { "path": "'"${AWSME}"'/bootstrap/ubuntu.sh" }}}}')
  bundle exec vagrant up
  id_instance="$(bundle exec ruby -e 'require "json"; puts JSON.load(File.read(".vagrant"))["active"]["default"]')"
  until_vbox "poweroff"

  # virtualbox
  bin/cook -j <(echo '{"run_list": ["vagrant"], "vagrant": { "box": "precise-server-cloudimg-amd64", "provision": { "shell": { "path": "'"${AWSME}"'/bootstrap/virtualbox.sh" }}}}')
  bundle exec vagrant up

  # bundling
  bin/cook -j <(echo '{"run_list": ["vagrant"], "vagrant": { "box": "precise-server-cloudimg-amd64", "provision": { "shell": { "path": "'"${AWSME}"'/bootstrap/finished.sh" }}}}')
  bundle exec vagrant provision
  bundle exec vagrant package
  mv package.box boxes/awsme.box
  bundle exec vagrant box remove awsme || true
  bundle exec vagrant box add awsme boxes/awsme.box
  bundle exec vagrant destroy -f

  # boot up new box
  bin/cook -j <(echo '{"run_list": ["vagrant"], "vagrant": { "box": "awsme" }}')
  bundle exec vagrant up
  id_instance="$(bundle exec ruby -e 'require "json"; puts JSON.load(File.read(".vagrant"))["active"]["default"]')"
  until_vbox "running"
  time until_port_open localhost "$(forwarded_ssh_port)"
  bundle exec vagrant ssh -- -l ubuntu
}

require sub "$BASH_SOURCE" "$@"
