#!/bin/bash

#/ NAME
#/     build clean -- builds a clean vagrant box based on awsme with customizations
#/
#/ SYNOPSIS
#/   bin/build clean
#/
#/ EXAMPLES
#/     $ bin/build clean

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require awsme
require build

# entry point
function main {
  cd $shome
  time build_clean "$@"
}

function build_clean {
  # boot up new box
  bin/cook -j <(echo '{"run_list": ["vagrant"], "vagrant": { "box": "awsme" }}')
  bundle exec vagrant destroy -f || true
  bundle exec vagrant up
  local id_instance="$(cat $shome/.vagrant/machines/default/virtualbox/id)"
  until_vbox "running"
  time until_port_open localhost "$(forwarded_ssh_port)"

  local tmp_ssh_config="$(mktemp -t XXXXXXXXX)"
  bundle exec vagrant ssh-config > "$tmp_ssh_config"
  local pth_custom="$1"; shift
  $pth_custom "$tmp_ssh_config" "$@"
  rm -f "$tmp_ssh_config"
}

require sub "$BASH_SOURCE" "$@"
