#!/usr/bin/env bash

#/ NAME
#/     puddle-init -- make a Python virtualenv
#/
#/ SYNOPSIS
#/     puddle init where

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

DEFINE_string python "python" "Path to python" p

# entry point
function main {
  local vhome="."

  local cmd_venv="$shome/libexec/virtualenv.py"

  (set +f; rm -f "$vhome/bin/python"* "$vhome/bin/virtualenv")
  (set +f; rm -rf "$vhome/lib/python"* "$vhome/include/python"*)
  $cmd_venv --extra-search-dir=$shome/vendor/puddle -p "$FLAGS_python" "$vhome"

  "$shome/bin/puddle" install pip2pi virtualenv

  rm -rf "$tmp_python"
}

require sub "$BASH_SOURCE" "$@"
