#!/usr/bin/env bash

#/ NAME
#/     puddle-install -- install cached package
#/
#/ SYNOPSIS
#/     puddle install [packages...]

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  local pth_cache="$shome/vendor/puddle"

  set +u; source $shome/bin/activate; set -u
  pip install --upgrade --index-url=file://"$pth_cache/simple" "$@"
}

require sub "$BASH_SOURCE" "$@"
