#!/bin/bash

#/ NAME
#/     shell -- sets up bash subshell with environment and paths
#/
#/ SYNOPSIS
#/     shell

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require build
require ec2

# entry point
function main {
  cd "$shome"

  prep_awscli

  bundle check 2>&1 > /dev/null || bundle --local --path vendor/bundle > /dev/null

  exec $SHELL
}

require sub "$BASH_SOURCE" "$@"
