#!/bin/bash

#/ NAME
#/     shell -- sets up bash subshell with environment and paths
#/
#/ SYNOPSIS
#/     shell

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require awsme
require build

# entry point
function main {
  cd "$shome"
  make
  bundle exec microwave -j <(dna)
  exec $SHELL
}

function dna {
  cat <<EOF
    { "run_list": ["awsme"] }
EOF
}

require sub "$BASH_SOURCE" "$@"
