#!/bin/bash

#/ NAME
#/     shell -- sets up bash subshell with environment and paths
#/
#/ SYNOPSIS
#/     shell

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require awsme
require build

DEFINE_string "working" "$shome" "Working directory" "w"
DEFINE_boolean "clean" "$FLAGS_FALSE" "Run sub-shell disabling profiles and prompts" "c"
DEFINE_string "shell" "$SHELL" "Run a different shell" "s"

# entry point
function main {
  cd "$FLAGS_working"

  if [[ "$FLAGS_clean" = "$FLAGS_TRUE" ]]; then
    unset PROMPT_COMMAND
    exec $FLAGS_shell --norc --noprofile
  else
    exec $FLAGS_shell
  fi
}

function dna {
  cat <<EOF
    { "run_list": ["awsme"] }
EOF
}

require sub "$BASH_SOURCE" "$@"
